# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        '/:year-:month-:day/:title'
relative_permalinks: true

# Setup
title:            Mattias Appelgren
tagline:          'This is the blog'
description:      '\f.(\x.f (x x)) (\x.f (x x))'
url:              http://blog.ppelgren.se
baseurl:          /

author:
  name:           'Mattias Appelgren'
  url:            http://blog.ppelgren.se

paginate:         5
