# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        '/:year-:month-:day/:title'
relative_permalinks: true

# Setup
title:            Mattias Appelgren
tagline:          'What is this?'
description:      '\f.(\x.f (x x)) (\x.f (x x))'
url:              https://mattias-.github.io
baseurl:          /

author:
  name:           'Mattias Appelgren'
  url:            https://mattias-.github.io

paginate:         5
