# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Mattias Appelgren
tagline:          'What is this?'
description:      '\f.(\x.f (x x)) (\x.f (x x))'
url:              http://mattias-.github.io
baseurl:          /

author:
  name:           'Mattias Appelgren'
  url:            http://mattias-.github.io

paginate:         5
